core/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.itemListView, name='index'),
    path('items/', views.itemListView, name='itemListView'),
    path('item/<int:pk>', views.ItemDetailView, name='item-detail'),

    # ItemInstance
    path('iteminstance/create/<int:pk>', views.ItemInstanceCreateView.as_view(), name='iteminstance-create'),
    path('iteminstance/delete/<int:pk>', views.ItemInstanceDeleteView, name='iteminstance-delete'),
    path('iteminstance/update/<int:pk>', views.ItemInstanceUpdateView, name='iteminstance-update'),
    path('iteminstance/toggleavailability/<int:pk>', views.ItemInstanceMakeToggleAvailability,
         name="iteminstance-toggle"),
    path('iteminstance/detail/<int:pk>', views.ItemInstanceDetailView, name='iteminstance-detail'),

    # Borrowing
    path('borrowing/create/<int:pk>', views.BorrowingCreateView.as_view(), name='borrowing-create'),
    path('borrowing/<int:pk>', views.BorrowingDetailView, name='borrowing-detail'),
    path('borrowing/extend/<int:pk>', views.BorrowingExtendOneWeek, name='borrowing-extend'),
    path('borrowing/returned/<int:pk>', views.BorrowingMarkAsReturned, name='borrowing-returned'),
    path('borrowing/pay/<int:pk>', views.PayOverdueFee, name="borrowing-pay"),

    # User
    path('users/', views.UserListView, name='user-list'),
    path('user/<int:pk>', views.UserDetailView, name='user-detail'),

    # Date update:
    # path('updatetime/', views.UpdateTime, name='update')

    # Item
    path('item/create', views.ItemCreateView.as_view(), name="item-create"),
    path('item/update/<int:pk>', views.ItemUpdateView.as_view(), name="item-update")


]

library/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('core/', include('core.urls')),
    path('', RedirectView.as_view(url='core/', permanent=True)),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

core/models.py
import datetime
from decimal import Decimal

from django.contrib import admin
from django.core.validators import MinValueValidator
from django.db import models

# Create your models here.
from django.urls import reverse
from django.contrib.auth.models import AbstractUser  # Required to assign User as a borrower


class Situation(models.Model):
    situation = models.CharField(max_length=200)
    yearly_subscription_price = models.DecimalField(max_digits=5, decimal_places=2)

    def __str__(self):
        return self.situation


class User(AbstractUser):
    # ban for two years if to many overdue items
    situation = models.ForeignKey(Situation, null=True, on_delete=models.SET_NULL)
    banned_until = models.DateTimeField(null=True, blank=True)
    subscription_end_date = models.DateField(null=True, blank=True)

    def __str__(self):
        return f"{self.first_name} {self.last_name}"


class Author(models.Model):
    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)
    date_of_birth = models.DateField(null=True, blank=True)
    date_of_death = models.DateField('Died', null=True, blank=True)

    class Meta:
        ordering = ['last_name', 'first_name']

    def get_absolute_url(self):
        return reverse('author-detail', kwargs={'pk': self.pk})

    def __str__(self):
        return f'{self.first_name} {self.last_name}'


class Genre(models.Model):
    """Model representing a genre"""
    name = models.CharField(max_length=200, help_text='Enter a genre')

    def __str__(self):
        return self.name


class Item(models.Model):
    """
        Item is the base class for all types of items (Books, DVDs and CDs). it regroups all the common fields.
        type specific fields are defined in derived classes (Book, CD, DVD)
    """
    # types will stay relativaly the same, no need to create a separate Model, using choices is enough
    book, dvd, cd = "book", "dvd", "cd"
    TYPES_CHOICES = [
        (book, 'Book'),
        (dvd, 'DVD'),
        (cd, 'CD'),
    ]

    """ Model representing an item (but not a specific copy) """
    title = models.CharField(max_length=200)
    type = models.CharField(max_length=200, choices=TYPES_CHOICES, default=book)
    # may have several authors
    author = models.ManyToManyField(Author, blank=True)

    genre = models.ManyToManyField(Genre, help_text='Select a genre for this item')
    description = models.TextField(max_length=1000, help_text='description of the item')

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        """Returns the url to access details for this item"""
        return reverse('item-detail', kwargs={'pk': self.pk})

    def get_instance_count(self):
        """Create a string for the Genre. This is required to display genre in Admin."""
        return self.iteminstance_set.count()

    def get_genres(self):
        return ", ".join([g.__str__() for g in self.genre.all()])

    def get_authors(self):
        return ", ".join([g.__str__() for g in self.author.all()])

    get_instance_count.short_description = "n° of items"


class ItemInstance(models.Model):
    available, on_loan, unavailable = 'a', 'l', 'u'

    STATUS_CHOICES = (
        (unavailable, 'Unavailable'),
        (on_loan, 'On loan'),
        (available, 'Available'),
    )

    as_new, good, poor = "as_new", "good", "poor"
    CONDITIONS_CHOICES = (
        (as_new, "As new"),
        (good, "Good"),
        (poor, "Poor"),
    )

    """ Model representing a specific copy of an item"""
    item = models.ForeignKey(Item, on_delete=models.RESTRICT)
    status = models.CharField(max_length=1, choices=STATUS_CHOICES, blank=False, null=False, default=available,
                              help_text="item status")
    condition = models.CharField(max_length=100, choices=CONDITIONS_CHOICES, blank=True, null=True,
                                 help_text="Item condition")

    def get_verbose(self):
        """Returns the url to access details for this item"""
        return "aaa"

    class Meta:
        ordering = ['item']

    def __str__(self):
        return f" (copy id {self.id})"


def get_initial_return_date():
    return datetime.datetime.now() + datetime.timedelta(days=30)


class Borrowing(models.Model):
    """ Model Representing a borrowing of an item """
    borrower = models.ForeignKey(User, null=True, on_delete=models.SET_NULL)
    item = models.ForeignKey(ItemInstance, null=True, on_delete=models.SET_NULL)
    due_date = models.DateTimeField(default=get_initial_return_date, help_text='Initially set to now + 30days')
    overdue_fee = models.DecimalField(max_digits=64, decimal_places=2, default=0, validators=[MinValueValidator(0)])
    overdue_fee_payed = models.BooleanField(default=False)
    borrowed = models.DateTimeField(default=datetime.datetime.now)
    returned = models.DateTimeField(null=True, blank=True)

    class Meta:
        ordering = ['due_date']

    def __str__(self):
        return f"due date : {self.due_date}"

core/views.py
import datetime

from django.db import connections
from django.db.models import prefetch_related_objects
from django.forms import model_to_dict
from django.http import Http404, HttpResponseRedirect
from django.shortcuts import render, redirect
from django.urls import reverse, reverse_lazy
from django.utils import timezone
from django.views import generic
from django.views.generic import CreateView, DeleteView, UpdateView

from sqlhelpers import get_object_by_pk, save_object_to_db, delete_object, update_iteminstance_status, \
    update_borrowing_due_date, update_borrowing_returned
from .forms import ItemInstanceForm, BorrowingForm, ItemForm
from .models import Item, ItemInstance, Author, Genre, Borrowing, User, Situation

# Create your views here.
from .update import update_fees_and_bans


def ItemDetailView(request, pk):
    active_borrowing_id = {}

    # Select the item (using raw SQL with helper function)
    item = get_object_by_pk(Item, pk)

    # fetch the authors (id and name)
    authors = Author.objects.raw(f"""
    SELECT (`core_item_author`.`item_id`) AS `_prefetch_related_val_item_id`,
       `core_author`.`id`,
       `core_author`.`first_name`,
       `core_author`.`last_name`
    FROM `core_author`
    INNER JOIN `core_item_author`
    ON (`core_author`.`id` = `core_item_author`.`author_id`)
    WHERE `core_item_author`.`item_id` IN ({pk})
    ORDER BY `core_author`.`last_name` ASC,
          `core_author`.`first_name` ASC""")

    # fetch genres

    genres = Genre.objects.raw(f"""
    SELECT (`core_item_genre`.`item_id`) AS `_prefetch_related_val_item_id`,
   `core_genre`.`id`,
   `core_genre`.`name`
    FROM `core_genre`
    INNER JOIN `core_item_genre`
    ON (`core_genre`.`id` = `core_item_genre`.`genre_id`)
    WHERE `core_item_genre`.`item_id` IN ({pk})
    """)

    # Select the item instances
    item_instances = ItemInstance.objects.raw(f"""
    SELECT `core_iteminstance`.`id`,
   `core_iteminstance`.`item_id`,
   `core_iteminstance`.`status`,
   `core_iteminstance`.`condition`
    FROM `core_iteminstance`
    WHERE `core_iteminstance`.`item_id` IN ({pk})
    ORDER BY `core_iteminstance`.`item_id` ASC
    """)

    n_instances = item_instances.__len__()

    # select active borrowings ids for the current item:
    cursor = connections['default'].cursor()
    item_instance_ids = [i.id for i in item_instances]
    active_borrowings_id = {}
    if item_instance_ids:
        active_borrowing_ids = cursor.execute("""
        SELECT `core_borrowing`.`item_id` AS iteminstance_id, `core_borrowing`.`id` AS borrowing_id
        FROM `core_borrowing`
        WHERE `core_borrowing`.`item_id` IN %s AND `core_borrowing`.`returned` IS NULL
        ORDER BY iteminstance_id ASC""", [item_instance_ids])
        active_borrowings_id = dict(cursor.fetchall())

    return render(request, 'item_detail.html',
                  context={'item': item,
                           'authors': authors,
                           'genres': genres,
                           'item_instances': item_instances,
                           'active_borrowings_id': active_borrowings_id,
                           'n_instances': n_instances, }
                  )


def itemListView(request):
    """ View function for homepage of site """
    context = {}
    # update fees and bans
    update_fees_and_bans(datetime.datetime.now())  # + datetime.timedelta(days=0)

    num_items = Item.objects.all().count()
    print(f"num items = {num_items}")
    num_instances = ItemInstance.objects.all().count()

    # Available books (status = 'a')
    num_instances_available = ItemInstance.objects.filter(status='a').count()

    items = Item.objects.prefetch_related('author', 'genre').all()

    items_raw = Item.objects.raw("SELECT * FROM core_item")

    context['items'] = zip(items_raw, items)

    context['num_books'] = len([i for i in items_raw if i.type == "book"])
    context['num_cds'] = len([i for i in items_raw if i.type == "cd"])
    context['num_dvds'] = len([i for i in items_raw if i.type == "dvd"])

    context['page_title'] = "Library Items"

    return render(request, 'index.html', context=context)


class ItemInstanceCreateView(CreateView):
    template_name = 'iteminstance-create.html'
    form_class = ItemInstanceForm

    def get_success_url(self):
        pk = self.kwargs['pk']
        return reverse_lazy('item-detail', kwargs={'pk': pk})

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        item = get_object_by_pk(Item, self.kwargs['pk'])
        context['item'] = item
        return context

    def form_valid(self, form):
        form.instance.item = get_object_by_pk(Item, self.kwargs['pk'])
        # save object to db using raw SQL helpher function
        save_object_to_db(form.instance)
        return HttpResponseRedirect(self.get_success_url())


def ItemInstanceDeleteView(request, pk):
    """
    Confirm delete view
    """
    obj = get_object_by_pk(ItemInstance, pk)
    success_url = reverse_lazy('item-detail', kwargs={'pk': obj.item_id})

    if request.method == "POST":
        obj.delete()
        return HttpResponseRedirect(success_url)

    context = {
        "object": obj,
        "success_url": success_url,
    }
    return render(request, "iteminstance_confirm_delete.html", context)


def ItemInstanceDetailView(request, pk):
    """ redirect to item detail"""
    cursor = connections['default'].cursor()
    cursor.execute(f"""SELECT item_id FROM core_iteminstance WHERE id = {pk}""")
    return redirect('item-detail', pk=cursor.fetchall()[0][0])


def ItemInstanceUpdateView(request, pk):
    """
    View to update the condition of the book
    """
    context = {}
    # fetch the object related to passed pk
    obj = get_object_by_pk(ItemInstance, pk=pk)
    success_url = reverse_lazy('item-detail', kwargs={'pk': obj.item_id})
    # pass the object as instance in form
    form = ItemInstanceForm(request.POST or None, instance=obj)

    if form.is_valid():
        form.save()
        return HttpResponseRedirect(success_url)

    # add form dictionary to context
    context["form"] = form
    context["success_url"] = success_url
    context["object"] = obj

    return render(request, "iteminstance_update_form.html", context)


def ItemInstanceMakeToggleAvailability(request, pk):
    """
    if iteminstance is unavailable, make available and vice-versa
    """
    iteminstance = get_object_by_pk(ItemInstance, pk)
    if iteminstance.status == "a":
        update_iteminstance_status(iteminstance, "u")
    elif iteminstance.status == "u":
        update_iteminstance_status(iteminstance, "a")

    return HttpResponseRedirect(reverse_lazy('item-detail', kwargs={'pk': iteminstance.item_id}))


# Borrowings ---------------------------------------------

class BorrowingCreateView(CreateView):
    template_name = 'borrowing-create.html'
    form_class = BorrowingForm

    def get_initial(self):
        initial = super().get_initial()
        initial['item'] = get_object_by_pk(ItemInstance, self.kwargs['pk'])
        return initial

    def get_success_url(self, item_id):
        return reverse_lazy('item-detail', kwargs={'pk': item_id})

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        item_instance = get_object_by_pk(ItemInstance, self.kwargs['pk'])
        context['item_instance'] = item_instance
        return context

    def form_valid(self, form):
        print(form.instance.item)
        print(form.instance.item)
        print(form.instance.item)
        print(form.instance.item)
        print(form.instance.item)
        print(form.instance.item)
        form.instance.item = get_object_by_pk(ItemInstance, self.kwargs['pk'])
        # save object to db using raw SQL helpher function
        if form.instance.item.status == "a":
            form.instance.borrowed = datetime.date.today()
            save_object_to_db(form.instance)
            # update status of itemInstance
            update_iteminstance_status(form.instance.item, "l")
        else:
            print("Book unavailable")

        return HttpResponseRedirect(self.get_success_url(form.instance.item.item_id))


def BorrowingDetailView(request, pk):
    context = {}
    # Select the item (using raw SQL with helper function)
    borrowing = get_object_by_pk(Borrowing, pk)
    # get related iteminstance
    borrowing.borrower = get_object_by_pk(User, borrowing.borrower_id)
    # get related item title
    item = get_object_by_pk(Item, borrowing.item.item_id)
    # get related user :
    if borrowing.item_id:
        borrowing.item = get_object_by_pk(ItemInstance, borrowing.item_id)

    context['borrowing'] = borrowing
    context['item'] = item
    return render(request, 'borrowing_detail.html', context=context)


def BorrowingExtendOneWeek(request, pk):
    """
    extend due_date by 1 week
    """
    borrowing = get_object_by_pk(Borrowing, pk)
    new_due_date = borrowing.due_date + datetime.timedelta(weeks=1)
    update_borrowing_due_date(borrowing, new_due_date)

    return HttpResponseRedirect(reverse_lazy('borrowing-detail', kwargs={'pk': borrowing.id}))


def BorrowingMarkAsReturned(request, pk):
    """
        Mark as returned with current date and set related iteminstance to available
    """
    borrowing = get_object_by_pk(Borrowing, pk)
    return_datetime = datetime.datetime.now()
    update_borrowing_returned(borrowing, return_datetime)

    itemintance = get_object_by_pk(ItemInstance, borrowing.item_id)
    update_iteminstance_status(itemintance, "a")

    return HttpResponseRedirect(reverse_lazy('borrowing-detail', kwargs={'pk': pk}))


# User Views ---------------------------------

def UserListView(request):
    context = {}
    users = User.objects.raw("SELECT * FROM `core_user`")

    context['users'] = users
    context['n_users'] = users.__len__()

    # get situations
    cursor = connections['default'].cursor()

core/templates/base_generic.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8"/>
  <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no"/>
  <meta name="description" content=""/>
  <meta name="author" content=""/>
  <title>Dashboard - SB Admin</title>
  <link href="https://cdn.jsdelivr.net/npm/simple-datatables@latest/dist/style.css" rel="stylesheet"/>
  {% load static %}
  <link href="{% static 'css/styles.css' %}" rel="stylesheet"/>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/js/all.min.js"
          crossorigin="anonymous"></script>
</head>
<body class="sb-nav-fixed">
<nav class="sb-topnav navbar navbar-expand navbar-dark bg-dark">
  <!-- Navbar Brand-->
  <a class="navbar-brand ps-3" href="{% url 'index' %}">Library</a>
  <!-- Sidebar Toggle-->
  <button class="btn btn-link btn-sm order-1 order-lg-0 me-4 me-lg-0" id="sidebarToggle" href="#!"><i
          class="fas fa-bars"></i></button>
  <!-- Navbar Search-->
  <div class="navbar-brand ps-3 m-4">Date : {% now "jS F Y H:i" %} </div>
  <form class="d-none d-md-inline-block form-inline ms-auto me-0 me-md-3 my-2 my-md-0">
  </form>
  <!-- Navbar-->
</nav>
<div id="layoutSidenav">
  <div id="layoutSidenav_nav">
    <nav class="sb-sidenav accordion sb-sidenav-dark" id="sidenavAccordion">
      <div class="sb-sidenav-menu">
        <div class="nav">
          <div class="sb-sidenav-menu-heading">Core</div>
          <a class="nav-link" href={% url "index" %}>
            <div class="sb-nav-link-icon"><i class="fas fa-book-open"></i></div>
            Items
          </a>
          <a class="nav-link" href={% url "user-list" %}>
            <div class="sb-nav-link-icon"><i class="fas fa-user"></i></div>
            Users
          </a>


          <div class="collapse" id="collapsePages" aria-labelledby="headingTwo" data-bs-parent="#sidenavAccordion">
            <nav class="sb-sidenav-menu-nested nav accordion" id="sidenavAccordionPages">
              <a class="nav-link collapsed" href="#" data-bs-toggle="collapse" data-bs-target="#pagesCollapseAuth"
                 aria-expanded="false" aria-controls="pagesCollapseAuth">
                Authentication
                <div class="sb-sidenav-collapse-arrow"><i class="fas fa-angle-down"></i></div>
              </a>
              <div class="collapse" id="pagesCollapseAuth" aria-labelledby="headingOne"
                   data-bs-parent="#sidenavAccordionPages">
                <nav class="sb-sidenav-menu-nested nav">
                  <a class="nav-link" href="login.html">Login</a>
                  <a class="nav-link" href="register.html">Register</a>
                  <a class="nav-link" href="password.html">Forgot Password</a>
                </nav>
              </div>
              <a class="nav-link collapsed" href="#" data-bs-toggle="collapse" data-bs-target="#pagesCollapseError"
                 aria-expanded="false" aria-controls="pagesCollapseError">
                Error
                <div class="sb-sidenav-collapse-arrow"><i class="fas fa-angle-down"></i></div>
              </a>
              <div class="collapse" id="pagesCollapseError" aria-labelledby="headingOne"
                   data-bs-parent="#sidenavAccordionPages">
                <nav class="sb-sidenav-menu-nested nav">
                  <a class="nav-link" href="401.html">401 Page</a>
                  <a class="nav-link" href="404.html">404 Page</a>
                  <a class="nav-link" href="500.html">500 Page</a>
                </nav>
              </div>
            </nav>
          </div>
        </div>
      </div>
      <div class="sb-sidenav-footer">
        {% if user %}
          <div class="small">Logged in as:</div>
          {{ user }}
        {% endif %}

      </div>
    </nav>
  </div>
  <div id="layoutSidenav_content">
    <main>
      <div class="container-fluid px-4">
        {% block title %}
        {% endblock %}
        {% block content %}{% endblock %}
      </div>
    </main>
    <footer class="py-4 bg-light mt-auto">
      <div class="container-fluid px-4">
        <div class="d-flex align-items-center justify-content-between small">
          <div class="text-muted">Library Management - Luke Halleman - Victor Lachenal</div>
          <div>
            <a href="#">Privacy Policy</a>
            &middot;
            <a href="#">Terms &amp; Conditions</a>
          </div>
        </div>
      </div>
    </footer>
  </div>
</div>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"
        crossorigin="anonymous"></script>
<script src="{% static 'js/scripts.js' %}"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.8.0/Chart.min.js" crossorigin="anonymous"></script>
<script src="{% static 'assets/demo/chart-area-demo.js' %}"></script>
<script src="{% static 'js/datatables-simple-demo.js' %}"></script>
<script src="https://cdn.jsdelivr.net/npm/simple-datatables@latest" crossorigin="anonymous"></script>
<script src="{% static 'assets/demo/chart-area-demo.js' %}"></script>
</body>
</html>

core/templates/borrowing-create.html
{% extends "base_generic.html" %}
{% block title %}
{% endblock %}
{% load crispy_forms_tags %}
{% block content %}
  {% if item_instance.status == "a" %}
    <div class="card mb-4 mt-4">
      <div class="card-header">
        <h4>Lend {{ item_instance }}</h4>
      </div>
      <div class="card-body">
        <div> <i class="fas fa-exclamation-triangle me-1"></i> A single user can borrow 3 books and 2 CDs/DVDs</div>
        <form method="post">{% csrf_token %}
          {{ form|crispy }}
          <input class="btn btn-primary mt-2" type="submit" value="Save">
        </form>
      </div>
    </div>
  {% else %}
    <div class="card mb-4 mt-4">
      <div class="card-header">
        <h4><i class="fas fa-exclamation-triangle me-1"></i> Copy currently not available (on loan or unavailabe)</h4>
      </div>
      <div class="card-body">
      </div>
    </div>
  {% endif %}
{% endblock content %}

core/templates/index.html
{% extends "base_generic.html" %}
{% block title %}
  <h1 class="mt-4">Items</h1>
{% endblock %}
{% block content %}
  <div class="card mb-4">
    <div class="card-header">
      Item counts
    </div>
    <div class="card-body">
      References :
      <ul>
        <li>Books : <b>{{ num_books }}</b></li>
        <li>CDs: <b>{{ num_cds }}</b></li>
        <li>DVDs : <b>{{ num_dvds }}</b></li>
      </ul>
    </div>
  </div>

  <div class="card mb-4">
    <div class="card-header">
      <div class=" d-flex justify-content-between">
        <h4> Items table </h4>
        <a class="btn btn-primary text-decoration-none" href="{% url "item-create" %}" role="button">
          <i class="fas fa-plus me-1"></i>
          Add a new item
        </a>
      </div>
    </div>
    <div class="card-body">
      <table id="itemstable">
        <thead>
        <tr>
          <th>Name</th>
          <th>Author(s)</th>
          <th>Type</th>
          <th>Genre</th>
          <th>Total copies</th>
        </tr>
        </thead>
        <tfoot>
        <tr>
          <th>Name</th>
          <th>Author(s)</th>
          <th>Type</th>
          <th>Genre</th>
          <th>Total copies</th>
        </tr>
        </tfoot>
        <tbody>
        {% for item, i in items %}
          <tr>
            <td><a href="{{ item.get_absolute_url }}">{{ item.title }}</a></td>
            <td>{{ i.get_authors }}</td>
            <td>
              {% if item.type == "cd" %}
                <i class="fas fa-compact-disc me-1"></i>
              {% elif item.type == "book" %}
                <i class="fas fa-book me-1"></i>
              {% elif item.type == "dvd" %}
                <i class="fas fa-film me-1"></i>
              {% endif %}
              {{ item.type }}
            </td>
            <td>{{ i.get_genres }}
            </td>
            <td>{{ i.iteminstance_set.count }}</td>
          </tr>
        {% endfor %}
        </tbody>

      </table>
    </div>
  </div>
{% endblock %}

core/templates/item_detail.html
{% extends "base_generic.html" %}
{% block title %}
{% endblock %}
{% block content %}
  <div class="card mb-4 mt-4">
    <div class="card-header d-flex justify-content-between">
      <h2>{{ item.title }}</h2>
      {% if item.type == "cd" %}
        <i class="fas fa-compact-disc me-1"></i>
      {% elif item.type == "book" %}
        <i class="fas fa-book me-1"></i>
      {% elif item.type == "dvd" %}
        <i class="fas fa-film me-1"></i>
      {% endif %}
    <a class="btn btn-primary text-decoration-none" href="{% url "item-update" item.id %}" role="button">
        <i class="fas fa-edit me-1"></i>
        Edit
      </a>
    </div>
    <div class="card-body">
      <ul>
        <li>
          <b>Author(s)</b> : {{ authors|join:", " }}
        </li>
        <li>
          <b>Genre(s)</b> : {{ genres|join:", " }}
        </li>
        <li><b>Description </b> : {{ item.description }}</li>
      </ul>
    </div>
  </div>
  <div class="card mb-4">
    <div class="card-header d-flex justify-content-between">
      <h4> Copies ({{ n_instances }})</h4>
      <a class="btn btn-primary text-decoration-none" href="{% url "iteminstance-create" item.id %}" role="button">
        <i class="fas fa-plus me-1"></i>
        Add a new copy
      </a>
    </div>
    <div class="card-body">
      <table id="itemstable">
        <thead>
        <tr>
          <th>Id</th>
          <th>Condition</th>
          <th>Status</th>
          <th>Status Actions</th>
          <th>Actions</th>
        </tr>
        </thead>
        <tfoot>
        <tr>
          <th>Id</th>
          <th>Condition</th>
          <th>Status</th>
          <th>Status Actions</th>
          <th>Actions</th>
        </tr>
        </tfoot>
        <tbody>
        {% for instance in item_instances %}
          <tr>
            <td>{{ instance.id }}</td>
            <td>{{ instance.get_condition_display }}</td>
            <td>{{ instance.get_status_display }}</td>
            <td>
              {% if instance.status == "u" %}
                <a class="btn-sm btn-light text-decoration-none" href="{% url "iteminstance-toggle" instance.id %}">make
                  available</a>
              {% elif instance.status == "a" %}
                <a class="btn-sm btn-primary text-decoration-none"
                   href="{% url "borrowing-create" instance.id %}"><i class="fas fa-plus"></i> lend</a>
                <a class="btn-sm btn-light text-decoration-none" href="{% url "iteminstance-toggle" instance.id %}">make
                  unavailable</a>
              {% elif instance.status == "l" %}
                {% load custom_filters %}
                <a
                        class="btn-sm btn-primary text-decoration-none"
                        href="{% url "borrowing-detail" active_borrowings_id|get_item:instance.id %}"><i
                        class="fas fa-eye"></i> see loan</a>

              {% endif %}
            </td>
            <td>
              <a class=" btn-sm btn-primary" href="{% url "iteminstance-update" instance.id %}">
                <i class="fas fa-edit"></i></a>
              <a class="btn-sm btn-danger" href="{% url "iteminstance-delete" instance.id %}">
                <i class="fas fa-trash-alt"></i></a>
            </td>
          </tr>
        {% endfor %}
        </tbody>
      </table>
    </div>
  </div>
{% endblock %}